# Generated by Django 3.2.9 on 2021-11-25 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='EAN',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='post',
            name='MOA',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 19, 45, 56, 954510, tzinfo=utc)),
        ),
    ]
