# Generated by Django 3.2.9 on 2021-11-25 19:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20211125_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EAN', models.CharField(blank=True, default='', max_length=16)),
                ('IMD', models.CharField(max_length=200)),
                ('QTY', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('MOA', models.CharField(blank=True, default='', max_length=20)),
                ('PRI', models.CharField(max_length=20)),
                ('TAX', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 11, 25, 19, 52, 49, 253462, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
